name: social_feed_reaction
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/Ambikadulal/social_feed_reaction

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen: ^5.2.0
  audioplayers: ^3.0.1
  path_provider: ^2.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
    - sounds/