name: social_feed_reaction
description: A dynamic Dart package for seamlessly integrating social reactions into your Flutter application. This fully customizable widget enables you to use your preferred emojis and assets while also providing a set of included sample icons.
version: 0.0.1+2
homepage: https://github.com/Ambikadulal/social_feed_reaction

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen: ^5.2.0
  audioplayers: ^5.1.0
  path_provider: ^2.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
    - sounds/